# Finding peaks discriminating callow and mature *F. sanguinea* workers

```{r warning=FALSE}
# devtools::install_github("mixOmicsTeam/mixOmics", ref = "143d31f9629bc83f1f27272ba6b7a2aaef0ee0e8")
suppressMessages({
  library(sangchem)
  library(dplyr)
  library(mixOmics)
})

# load data
data("development_data")
data("mass_spectra_data")

DA_data <- dplyr::filter(development_data, caste=="worker", !remarks %in% c("aggression actor", "aggression target", "queenless colony")) %>%
  dplyr::select(colony, species, callow, census_date, chromatogram_ID, sang_prop) %>%
  split(list(.$colony, .$census_date), drop=TRUE) %>%
  lapply(function(x){if(sum(x$callow)==0) return(NULL); x}) %>%
  {function(x) x[!unlist((lapply(x, is.null)))]}() %>%
  purrr::map2(seq_along(.), function(x,y){x$group <- y; x}) %>%
  {function(x) do.call(rbind, x)}()

Y <- (DA_data$callow==1) + (DA_data$species=="F. sanguinea")

peak_prop <- peak_proportions_table(mass_spectra_data[mass_spectra_data$chromatogram_ID %in% DA_data$chromatogram_ID,])
peak_prop <- peak_prop[match(DA_data$chromatogram_ID, rownames(peak_prop)),]
# remove absent peaks
peak_prop <- peak_prop[,apply(peak_prop,2,function(x) sum(x)>0)]
peak_prop <- freq_abun_QC(peak_prop, freq_cutoff = 0.3, abundance_cutoff = 0.005)
# replace zeros with a small number before transformation
peak_prop[peak_prop==0] <- 10^-16
# apply central log ratio transformation
peak_transformed <- t(apply(peak_prop, 1, clr_transformation))
PCA_callow_discr <- prcomp(peak_transformed, scale. = TRUE)
PCA_callow_discr$x <- withinVariation(PCA_callow_discr$x, data.frame(DA_data$group))
```
```{r}
set.seed(1342)
discr_analysis_callow <- splsda(PCA_callow_discr$x, Y=Y ,multilevel=DA_data$group, 
                                ncomp=7, scale = FALSE)
plotIndiv(discr_analysis_callow, legend=TRUE,ellipse=TRUE,comp=1:2)

perf.discr_analysis_callow <- perf(discr_analysis_callow, 
                                validation = "Mfold", 
                                folds = 4, 
                           progressBar = FALSE, 
                           auc = TRUE, 
                           nrepeat = 30,
                           scale = FALSE)
plot(perf.discr_analysis_callow, col = color.mixo(1:3), sd = TRUE, legend.position = "horizontal")
selected_n <- perf.discr_analysis_callow$choice.ncom["overall", "max.dist"]
discr_analysis_callows_tuned <- tune.splsda(PCA_callow_discr$x,
                                   Y=Y,
                                   nrepeat = 30,
                                   folds = 4,
                                   ncomp = perf.discr_analysis_callow$choice.ncomp[1,1],
                                   test.keepX = seq(1:dim(PCA_callow_discr$x)[2]), 
                                   dist = 'max.dist',
                                   validation = 'Mfold',
                                   measure = "BER",
                                   progressBar = FALSE,
                                   scale = FALSE) 

discr_analysis_callows_res <- splsda(PCA_callow_discr$x,Y=Y,
                      multilevel= DA_data$group,
                      keepX=discr_analysis_callows_tuned$choice.keepX,
                      ncomp=selected_n,
                      scale = FALSE)

plotIndiv(discr_analysis_callows_res,
          legend=TRUE, ellipse=TRUE, comp=1:2)
```

## Determining callow markers
```{r}
set.seed(2341)
n_obs <- 10^5
n_var <- dim(peak_prop)[2]
x <- exp(5*runif(n_obs * n_var))
m = matrix(x, nrow = n_obs, ncol=n_var)
m <- m/rowSums(m)
transformed_m <- t(apply(m, 1, clr_transformation))
colnames(m)  <- colnames(peak_prop)
colnames(transformed_m) <- paste0("peak_", colnames(m))
df <- as.data.frame(transformed_m)
df$y <- calculate_SII(m, discr_analysis_callows_res, PCA_callow_discr, predicted_category=3)[,2]
```
```{r}
set.seed(4563)
p_val = c()
peak_coefficients <- c()
selected_residuals <- round(seq(1,n_obs,length.out=3000))
for(peak in colnames(transformed_m)){
  print("peak")
  model <- lm(formula(paste0("y~1 + ", peak)), data =df)
  print(summary(model))
  hist(residuals(model), breaks = 50, main = paste0("residuals ", peak))
  print(shapiro.test(residuals(model)[selected_residuals]))
  peak_coefficients <- c(peak_coefficients, model$coefficients[2])
}
```

```{r}
compounds <- c()
for (peak in colnames(peak_prop)){
  compounds <- c(compounds, mass_spectra_data[mass_spectra_data$peak_ID==peak,"identification"][1])
}
df_importance <- data.frame(peak_ID=colnames(peak_prop), coefficient = peak_coefficients, identification=compounds) 
peaks_callow <- colnames(peak_prop)[df_importance$coefficient>=0.004]
print(df_importance[order(df_importance$coefficient),])
```

## Determining mature *F. sanguinea* markers
```{r}
df$y <- calculate_SII(m, discr_analysis_callows_res, PCA_callow_discr, predicted_category=2)[,2]
set.seed(4563)
p_val = c()
peak_coefficients <- c()
for(peak in colnames(transformed_m)){
  print("peak")
  model <- lm(formula(paste0("y~1 + ", peak)), data =df)
  print(summary(model))
  hist(residuals(model), breaks = 50, main = paste0("residuals ", peak))
  print(shapiro.test(residuals(model)[selected_residuals]))
  peak_coefficients <- c(peak_coefficients, model$coefficients[2])
}
compounds <- c()
for (peak in colnames(peak_prop)){
  compounds <- c(compounds, mass_spectra_data[mass_spectra_data$peak_ID==peak,"identification"][1])
}
df_importance <- data.frame(peak_ID=colnames(peak_prop), coefficient = peak_coefficients, identification=compounds) 
peaks_mature <- colnames(peak_prop)[df_importance$coefficient>=0.004]
print(df_importance[order(df_importance$coefficient),])
```

```{r eval=FALSE}
globals <- readRDS(system.file("globals.rds", package="sangchem"))
globals[["peaks_callow"]] <- as.numeric(peaks_callow)
globals[["peaks_mature"]] <- as.numeric(peaks_mature)
saveRDS(globals, system.file("globals.rds", package="sangchem"))
```

## Session info
```{r}
print(sessionInfo())
```
