---
title: "Changes of CHCs amount over time"
author: "Tomasz Włodarczyk"
date: "7-12-2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this report we will check how the all CHCs or their specific subset changes in ants
of both species as colony develops. 

```{r}
suppressMessages({
library(sangchem)
library(dplyr)
library(lme4)
library(lmerTest)
library(DHARMa)
})
# load data
data("development_data")
load_globals()
dev_samples <- filter(development_data, caste=="worker",!is.na(head_width), !remarks %in% c("aggression actor", "aggression target", "queenless colony"), callow==0) %>%
  dplyr::select(chromatogram_ID, species, colony, sang_prop, head_width, mass, census_date)
dev_samples$corrected_mass <- dev_samples$mass/dev_samples$head_width^2*10^6
```

# Change in to total CHCs mass
## *F. sanguinea*
```{r}
model_input <- dev_samples[dev_samples$species=="F. sanguinea",]
lm_model <- lmer(I(log(corrected_mass)) ~ sang_prop  + (1|colony) +(1 | colony:census_date), data=model_input)
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model))
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE)
plot(simulationOutput)
```

## *F. fusca*
```{r}
model_input <- dev_samples[dev_samples$species=="F. fusca",]
lm_model <- lmer(I(log(corrected_mass)) ~ sang_prop  + (1|colony), data=model_input)
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model))
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE)
plot(simulationOutput)
```

# Change of the CHCs associated with *F. sanguinea*
## *F. sanguinea* ants
```{r}
model_input <- dev_samples[dev_samples$species=="F. sanguinea",]
model_input$corrected_mass <- model_input$corrected_mass*subsample_proportion(peaks_sang, model_input$chromatogram_ID)
lm_model <- lmer(I(log(corrected_mass)) ~ sang_prop +(1 | colony:census_date), data=model_input)
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model))
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE)
plot(simulationOutput)
```

## *F. fusca* ants
```{r}
model_input <- dev_samples[dev_samples$species=="F. fusca",]
model_input$corrected_mass <- model_input$corrected_mass*subsample_proportion(peaks_sang, model_input$chromatogram_ID)
lm_model <- lmer(corrected_mass ~ sang_prop +(1|colony:census_date) + (1|colony), data=model_input)
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model))
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE)
plot(simulationOutput)
```

# Change of the CHCs associated with *F. fusca*
## *F. sanguinea* ants
```{r}
model_input <- dev_samples[dev_samples$species=="F. sanguinea",]
model_input$corrected_mass <- model_input$corrected_mass*subsample_proportion(peaks_fusca, model_input$chromatogram_ID)
lm_model <- lmer(I(log(corrected_mass)) ~ sang_prop +(1 | colony:census_date) + (1 | colony), data=model_input)
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model))
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE)
plot(simulationOutput)
```

## *F. fusca* ants
```{r}
model_input <- dev_samples[dev_samples$species=="F. fusca",]
model_input$corrected_mass <- model_input$corrected_mass*subsample_proportion(peaks_fusca, model_input$chromatogram_ID)
lm_model <- lmer(I(log(corrected_mass)) ~ sang_prop + (1 | colony), data=model_input)
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model))
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE)
plot(simulationOutput)
```
