# Change in the CHC profile of separated callow *F. sanguinea* ants
```{r warning=FALSE}
suppressMessages({
  library(sangchem)
  library(dplyr)
  library(lmerTest)
  library(DHARMa)
})

# load data
data("separation_experiment_data")
data("mass_spectra_data")
```

## Change in total CHC amount over time
```{r}
separation_data <- filter(separation_experiment_data, treatment_id<5)
separation_data$normalized_mass <- separation_data$mass*CHC_normalizer("F. sanguinea", separation_data$head_width)
# remove row 74 which is an outlier
lm_model <- lmer(I(sqrt(normalized_mass))~mean_delta+(1|colony), data = separation_data[-74,])
print(summary(lm_model))

# model diagnostics
hist(residuals(lm_model), main="Model conditional residuals", xlab="Residuals")
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE, n=1e4)
plot(simulationOutput)
```

## Change in the amount of compounds characteristic of callow *F. sanguinea*
```{r}
load_globals()
separation_data$normalized_mass_part <- separation_data$normalized_mass * subsample_proportion(peaks_callow, separation_data$chromatogram_ID)
lm_model <- lmer(log(normalized_mass_part)~mean_delta+(1|colony), data = separation_data)
print(summary(lm_model))
hist(residuals(lm_model), main="Model conditional residuals", xlab="Residuals")
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE, n=1e4)
plot(simulationOutput)
```

## Change in the amount of compounds characteristic of *F. sanguinea*
```{r}
separation_data$normalized_mass_part <- separation_data$normalized_mass * subsample_proportion(peaks_sang, separation_data$chromatogram_ID)
lm_model <- lmer(I(sqrt(normalized_mass_part))~poly(mean_delta,1)+(1|colony), data = separation_data[-c(69, 74),])
print(summary(lm_model))
hist(residuals(lm_model), main="Model conditional residuals", xlab="Residuals")
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE, n=1e4)
plot(simulationOutput)
```

## Change in the amount of compounds characteristic of *F. fusca*
```{r}
separation_data$normalized_mass_part <- separation_data$normalized_mass * subsample_proportion(peaks_fusca, separation_data$chromatogram_ID)
lm_model <- lmer(log(normalized_mass_part)~mean_delta+(1|colony), data = separation_data)
print(summary(lm_model))
hist(residuals(lm_model), main="Model conditional residuals", xlab="Residuals")
shapiro.test(residuals(lm_model))
simulationOutput <- simulateResiduals(fittedModel = lm_model, plot = FALSE, n=1e4)
plot(simulationOutput)
```
