---
title: "Comparison of CHC amount and proportions in between different categories of individuals"
author: "Tomasz Włodarczyk"
date: "28-11-2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r warning=FALSE}
suppressMessages({
  library(sangchem)
  library(dplyr)
  library(ggpubr)
  library(rstatix)
})

# load data
data("development_data")
```

# Difference in the total CHC amount between callow and mature *F. sanguinea*
```{r}
test_data <- filter(development_data, species == "F. sanguinea") %>% select(census_date, colony, corrected_mass,callow)
test_data_mature <- filter(test_data, callow == 0) %>% colony_weighted_mean()
test_data_mature$callow <- 0
test_data_callow <- filter(test_data, callow == 1) %>% colony_weighted_mean()
test_data_callow $callow <- 1
colonies <- intersect(test_data_mature$colony, test_data_callow$colony)
test_df <- rbind(test_data_callow, test_data_mature)
test_df <- test_df[test_df$colony %in% colonies,]
test_df <- test_df[order(test_df$colony),]
wilcox_test(test_df, corrected_mass~callow, paired=TRUE)
test_df$callow <- factor(test_df$callow)
test_stats <- wilcox_test(test_df, corrected_mass~callow, paired=TRUE) %>%
  add_significance("p") %>%
  add_xy_position(x="callow", dodge=0.8, fun="max")
ggboxplot(test_df, x="callow", y="corrected_mass")+
  scale_y_continuous(expand = expansion(mult=c(0.02,0.1)))+
  stat_pvalue_manual(test_stats, label="p", tip.length = 0, size=3.5)
```

```{r}
print(sessionInfo())
```
